import type { Metadata } from "next";
import Navbar from "../src/components/navbar/navbar";
import { Mulish } from "next/font/google";
import "./globals.css";
import { ProjectProvider } from "../src/store/provider";

const mulish = Mulish({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={mulish.className}>
        <ProjectProvider>
          <Navbar />
          {children}
        </ProjectProvider>
      </body>
    </html>
  );
}
